### ISSUE TITLE
Package libc6:amd64 not installed

### ISSUE THREAD

**Issue by nobuto-m** [mikix/deb2snap#6]
On amd64 host, I got the error "Package libc6:amd64 not installed".

```
$ bash -x ./deb2snap -d 15.04 hello
...
++ dpkg -S /lib/x86_64-linux-gnu/libc.so.6
++ sed 's/: .*//'
+ PACKAGES=' hello libc6:amd64'
...
++ ./tools/dep-tree --manifest /home/ubuntu/.cache/snappy-preload/manifests/ubuntu-core-15.04-core-amd64.manifest hello libc6:amd64
Package libc6:amd64 not installed
```

How to reproduce:

create vivid LXC container
```
$ sudo lxc-create -t ubuntu-cloud -n vivid-lxc -- --release vivid -S ~/.ssh/id_rsa.pub
```

prepare deb2snap
```
$ sudo apt-add-repository ppa:snappy-dev/tools
$ sudo apt update

$ sudo apt install cmake gcc-multilib ubuntu-snappy-cli git dpkg-dev

$ git clone https://github.com/mikix/deb2snap
$ cd deb2snap
```
run deb2snap
```
$ sudo apt install hello
$ ./deb2snap -d 15.04 hello
Package libc6:amd64 not installed
```

libc6:amd64 is certainly installed.
```
$ apt-cache policy libc6:amd64
libc6:
  Installed: 2.21-0ubuntu4
  Candidate: 2.21-0ubuntu4
  Version table:
 *** 2.21-0ubuntu4 0
        500 http://archive.ubuntu.com/ubuntu/ vivid/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by bladernr** [comment]
Going to suggest this is not just an AMD64 thing...

I have built deb2snap within a pbuilder armhf environment just as nobuto-m did in the first issue he raised.  I then installed isc-dhcp-server and attempted to build a snap from that.

Instead, I get an error like the one nobuto-m saw, only for the armhf port of libc6:
```root@klaatu:/deb2snap# ./deb2snap dhcpd
Package libc6:armhf not installed
```
And likewise, it is installed:
```root@klaatu:/deb2snap# apt-cache policy libc6:armhf
libc6:
  Installed: 2.21-0ubuntu4
  Candidate: 2.21-0ubuntu4
  Version table:
 *** 2.21-0ubuntu4 0
        500 http://ports.ubuntu.com/ vivid/main armhf Packages
        100 /var/lib/dpkg/status
```

**Comment by bladernr** [comment]
Removing the try/except around the addDeps() stuff results in this trace from apt.cache:

root@klaatu:/deb2snap/tools# ./dep-tree libc6:armhf
Adding Deps for libc6:armhf
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 198, in __getitem__
    return self._weakref[key]
  File "/usr/lib/python3.4/weakref.py", line 125, in __getitem__
    o = self.data[key]()
KeyError: 'libc6:armhf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./dep-tree", line 76, in <module>
    addDeps(args.packages)
  File "./dep-tree", line 56, in addDeps
    installedPkg = cache[p].installed
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 205, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'libc6:armhf'"

**Comment by bladernr** [comment]
Ok, it's because the packages refer to libc6:ARCH where apt cache actually just refers to it as libc6, which is, I think, exactly what nobuto-m mentioned in the comment he removed:

In [5]: cache['vim'].installed
Out[5]: <Version: package:'vim' version:'2:7.4.052-1ubuntu3'>

In [7]: cache['libc6:amd64'].installed
Out[7]: <Version: package:'libc6' version:'2.19-0ubuntu6.6'>

**Comment by bladernr** [comment]
FWIW, I fired up python3 in that environment and generated the trace directly:
```
Python 3.4.3 (default, Mar 26 2015, 23:09:09) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import apt
>>> cache = apt.Cache()
>>> cache['libc6:armhf'].installed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 198, in __getitem__
    return self._weakref[key]
  File "/usr/lib/python3.4/weakref.py", line 125, in __getitem__
    o = self.data[key]()
KeyError: 'libc6:armhf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 205, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'libc6:armhf'"
>>> 
```
And then tried again with no arch:
```
>>> cache['libc6'].installed
<Version: package:'libc6' version:'2.21-0ubuntu4'>
```

**Comment by mikix** [comment]
OK, try now.  I think all the systems I tried it on were multi-arch-enabled ones.  I think it was failing on single-arch systems.  Hopefully my code change will help there.

**Comment by bladernr** [comment]
Yep, as discussed on IRC, it builds now on my RPi.  Thanks a lot!  One suggestion for Launchpad though, if you end up packaging this, you need to add the following at a minimum as dependencies:

make (the instructions list cmake, but at least on some images like the Docker Ubuntu image you turned me on to, make is not installed).

dh-exec (will also pull in debhelper and some others that may also not be installed on some build systems initially).

Of course, that only applies if you are packaging this as a deb, thus far, I've only pulled the bzr and github trees and built from scratch.

**Comment by anthonywong** [comment]
On amd64, runs 'sudo dpkg --add-architecture i386'. This fixes for me.
